word='Pakistan'
print('character in position 0:  ', word[0])
print('character in position 5:  ', word[5])
print("last character:  ", word[-1])
print('second last character:  ', word[-2])
print("Character at position -6:  ", word[-6])
print('character from position 0 (included) to position 2 (excluded):  ', word[0:2])
print('character from position 2 (included) to position 5 (excluded):  ', word[2:5])
print('word[:2] + word[2:]= ', word[:2] + word[2:])
print('word[:4] + word[4:]=  ',word[:4] + word[4:])
print('character from the beginning to position 2 (excluded):  ', word[:2])
print('character from position 4 (included) to last character:  ', word[4:])
print('character from second last (included) to the end:  ', word[-2:])
print('j + word[1:]:  ', 'j' + word[1:] )
print('word[:2] + Pak:  ', word[:2] + 'Pak')
print('Length of the string:  ', len(word))
print('Complete word:  ', word)
